services:
  attacker:
    build: ./attacker
    container_name: unix-lab-attacker
    networks:
      - lab_net
    depends_on:
      - target

  target:
    build: ./target
    container_name: unix-lab-target
    networks:
      - lab_net
    ports:
      - "8080:8080"
    environment:
      AUDIT_TOKEN: unix-cyber-lab-readonly-audit
    volumes:
      - lab_logs:/var/log/unix-cyber-lab

  defender:
    build: ./defender
    container_name: unix-lab-defender
    networks:
      - lab_net
    volumes:
      - lab_logs:/var/log/unix-cyber-lab:ro
    command: ["sleep", "infinity"]

  dashboard:
    build: ./dashboard
    container_name: unix-lab-dashboard
    networks:
      - lab_net
    ports:
      - "3000:3000"
    environment:
      AUDIT_TOKEN: unix-cyber-lab-readonly-audit
    volumes:
      - lab_logs:/var/log/unix-cyber-lab
    depends_on:
      - target
      - attacker

networks:
  lab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24

volumes:
  lab_logs:
